# File: .github/workflows/deploy.yml
name: CI/CD for React App on Amazon Linux (EC2)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            # Update packages
            sudo yum update -y

            # Install Nginx if not present
            sudo amazon-linux-extras enable nginx1
            sudo yum install -y nginx

            # Create custom NGINX directory layout (Amazon Linux doesn't have sites-available)
            sudo mkdir -p /etc/nginx/sites-available
            sudo mkdir -p /etc/nginx/sites-enabled

            # Include sites-enabled in main config if not already
            if ! grep -q 'include /etc/nginx/sites-enabled/\*;' /etc/nginx/nginx.conf; then
              sudo sed -i '/http {/a \\tinclude /etc/nginx/sites-enabled/*;' /etc/nginx/nginx.conf
            fi

            # Write NGINX config directly (no nano in CI!)
            cat << 'EOF' | sudo tee /etc/nginx/sites-available/react-app.conf > /dev/null
            upstream react_app {
                server 127.0.0.1:3000;
            }

            server {
                listen 80 default_server;
                listen [::]:80 default_server;
                server_name _;

                location / {
                    proxy_pass http://react_app;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;
                }
            }
            EOF

            # Enable the config
            sudo ln -sf /etc/nginx/sites-available/react-app.conf /etc/nginx/sites-enabled/react-app.conf

            # Test and reload NGINX
            sudo nginx -t
            sudo systemctl enable nginx
            sudo systemctl restart nginx

            # Install Docker if not already installed
            if ! command -v docker &> /dev/null; then
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi

            # Pull latest code & build Docker image
            cd ~
            rm -rf react-app
            mkdir react-app
            cd react-app

            git clone https://github.com/${{ github.repository }} .
            git checkout main

            # Build Docker image
            sudo docker build -t react-app:latest .

            # Remove old container if it exists
            sudo docker stop react-app || true
            sudo docker rm react-app || true

            # Run new container on port 3000 → container port 80
            sudo docker run -d --name react-app -p 3000:80 react-app:latest

            # Clean up dangling images
            sudo docker image prune -f
